### ISSUE TITLE
Feature Request for ICD-9

### ISSUE THREAD

**Issue by drrckln** [yubin-park/drgpy#1]
I am looking for something similar that uses ICD-9-CM, as I wish to analyze older claims data. 

Is it possible to modify the program to do so? CMS does publish the [final rule tables](https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/AcuteInpatientPPS/Acute-Inpatient-Files-for-Download.html) going back to ~2006, which includes MCC/CC lists and exclusion lists. (I don't fully understand how the grouping algorithm works, so maybe this is insufficient.)

If you can point me to another resource, I'd also be very grateful.

**Comment by yubin-park** [comment]
Thanks for the interest, @drrckln! I probably need to look at the details of the data files to assess the level of difficulties, but allow me to suggest a quick and easy solution for your problem.

You can convert ICD9 diagnosis/procedure codes to ICD10 using General Equivalence Mapping (GEM). Please see 
- [ICD9 dx to ICD10 dx](https://www.cms.gov/Medicare/Coding/ICD10/2018-ICD-10-CM-and-GEMs.html)
- [ICD9 procedure to ICD10 procedure](https://www.cms.gov/Medicare/Coding/ICD10/2018-ICD-10-PCS-and-GEMs.html)

After converting ICD9 codes to ICD10 codes, and then you can apply this `drgpy` to get the corresponding DRG? Let me know if this solves your problem. Best,

**Comment by drrckln** [comment]
Ah, that could work. Thanks! I saw this quote at some point:

> "From a recent study conducted by 3M comparing the ICD-9-CM grouper to the ICD-10 grouper based on recoding patient records, they estimated that slightly more than 99% of the cases showed no change in MS-DRG when coded in ICD-10."

But I cannot recall which document I pulled this quote from, and it seemed to be from around the ICD-9 to ICD-10 switch, eg ~2014. It looks like CMS took pains to keep MS-DRG groupings stable then, but it's unclear to me if that's still the case 5 years later.

If I take 2010 dx/pcs codes, convert them, and apply `drgpy`, do you know if it's still 99%+ likely to have the same MS-DRG assigned as it was originally in 2010?

**Comment by drrckln** [comment]
I discovered that CMS's freely released MS-DRG grouper software applies the correct grouper version based on claim date.

**Comment by yubin-park** [comment]
Yes, you mean the Java application: https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/AcuteInpatientPPS/MS-DRG-Classifications-and-Software.html
I think there are a couple of other interfaces that you can download as well. 
This package is developed to easily integrate into other Python analytics stacks. If you are okay with running as a separate application, I recommend using those applications out there.

Regarding your question, I don't know if it will maintain 99%+ match with the conversion with `drgpy`, unless I have some data to compare to; sorry for not providing much insight on this.

**Comment by yubin-park** [comment]
Closing the original issue as it can be addressed with other packages.
