### ISSUE TITLE
Update to version 38.1

### ISSUE THREAD

**Issue by nvergos** [yubin-park/drgpy#10]
2021 claims follow the updated logic of the v38.1 grouper: https://www.cms.gov/files/zip/icd-10-ms-drg-definitions-manual-files-v381-text.zip

The data files format is still the same, but I believe additional changes need to be made in the individual .py files. Can you guide on how to implement? I'd be happy to tackle this.

**Comment by yubin-park** [comment]
@nvergos I would be happy to put your name on the collaborators on this project. Let me know if you want to hop on a quick call how we can do this together - you know my email address. Thanks!

**Comment by joshgel** [comment]
also willing to work on this

**Comment by bzsaindon** [comment]
@yubin-park - I would be willing to help updating to v39.1 if you are willing to provide a bit of guidance on what needs to be changed in the .py files :) Thank you!

**Comment by yubin-park** [comment]
@bzsaindon @joshgel @nvergos sorry for an extremely delayed response on this. Let me coordinate some time that I can provide some knowledge dump on this. Thanks so much!

**Comment by bzsaindon** [comment]
@yubin-park Thank you - I look forward to it!

**Comment by nvergos** [comment]
Thanks, @yubin-park! Looking forward to it too!

**Comment by yubin-park** [comment]
@bzsaindon @nvergos @joshgel could you check my calendar and let me know what time works for you all? 
https://calendly.com/d/dj7-gzd-354/30-minute-meeting

**Comment by bzsaindon** [comment]
Thank you @yubin-park - I selected 9a for 3/11, but I am generally free 8-12p on most weekday mornings.  I also can be available during the afternoon too, if that suits everyone else.

**Comment by joshgel** [comment]
https://github.com/JeredLinares/drgpy

**Comment by yubin-park** [comment]
Thanks, @joshgel, for sharing the repo! @bzsaindon and I plan to do something similar to the folked branch you shared.

**Comment by yubin-park** [comment]
v39 https://www.cms.gov/files/zip/icd-10-ms-drg-definitions-manual-files-v39.zip

**Comment by yubin-park** [comment]
I updated the repository to handle different versions. When you are initializing the engine, you can put the version parameter. However, the later versions are not tested. Will put some more test scripts in the future.
