### ISSUE TITLE
`dx_pttrn` excludes COVID-19 codes

### ISSUE THREAD

**Issue by mdbecker** [yubin-park/drgpy#13]
Thanks for the great package! We have a large DB of codes and DRGs assigned at a large regional hospital system and we've been looking at cases where this library disagrees with the billed DRGs. One high volume case is patients with a primary DX of U071 COVID-19. The CMS files show that these patients should be assigned DRG 177-179 but `drgpy` returns DRG 000. This seems to be due to `dx_pttrn` excluding these codes on [line 6 of _mdcsrdr.py](https://github.com/yubin-park/drgpy/blob/5223489d6fa48b26708e2292542b4c3354973962/drgpy/_mdcsrdr.py#L6). I looked through the history and couldn't figure out why the code was written this way. Obviously this code was written before COVID-19. Is there a reason to exclude 'U' codes from this library? If not, may I submit a pull request to fix this?

Thanks!

**Comment by yubin-park** [comment]
@mdbecker sorry for this long overdue reply. I just pushed a fix on this. Thanks so much!
