### ISSUE TITLE
How to print descriptions of DRG and MDC?

### ISSUE THREAD

**Issue by Raghu17s** [yubin-park/drgpy#3]
Hi,

After finding the final DRG using dx_lst and pr_lst, how can I print its description and MDC?
Is there any way to print CC and MCC for ICD codes as well?

**Comment by yubin-park** [comment]
Good idea. Let me update the library with some new functions.

**Comment by Raghu17s** [comment]
Hi @yubin-park 

I printed DRG description and MDC just by making using of Appendix A. It was just a mapping

Thank you

**Comment by yubin-park** [comment]
Closing the issue for now. Seems Raghu founded a solution.
