### ISSUE TITLE
Wrong DRG 807?

### ISSUE THREAD

**Issue by Raghu17s** [yubin-park/drgpy#4]
Hi folks,

I have Dx ICD of O80, Z370, and procedure ICD as 10D07Z3. 
It should output DRG as 807 according to MS-DRG software and https://icd10coded.com/ms-drg/mdc-14/807/?view=pcs. 
But it is giving 768. 
Could someone help to correct the DRG?

**Comment by yubin-park** [comment]
Sorry for the delayed response. Will check in a few weeks. Best,

**Comment by yubin-park** [comment]
@Raghu17s I looked up the document, and it seems Z370 can be either DRG 768 or DRG 807 depending on the operating room procedures. If no OR procedures, then it chooses to be DRG 768.
`DRG 805 VAGINAL DELIVERY WITHOUT STERILIZATION/D&C WITH MCC
DRG 806 VAGINAL DELIVERY WITHOUT STERILIZATION/D&C WITH CC
DRG 807 VAGINAL DELIVERY WITHOUT STERILIZATION/D&C WITHOUT CC/MCC

SECONDARY DIAGNOSIS

  Z370  Single live birth
  Z371  Single stillbirth
  Z372  Twins, both liveborn
  Z373  Twins, one liveborn and one stillborn
  Z374  Twins, both stillborn
  Z3750 Multiple births, unspecified, all liveborn
  Z3751 Triplets, all liveborn
  Z3752 Quadruplets, all liveborn
  Z3753 Quintuplets, all liveborn
  Z3754 Sextuplets, all liveborn
  Z3759 Other multiple births, all liveborn
  Z3760 Multiple births, unspecified, some liveborn
  Z3761 Triplets, some liveborn
  Z3762 Quadruplets, some liveborn
  Z3763 Quintuplets, some liveborn
  Z3764 Sextuplets, some liveborn
  Z3769 Other multiple births, some liveborn
  Z377  Other multiple births, all stillborn
  Z379  Outcome of delivery, unspecified

	AND OPERATING ROOM PROCEDURES

  10D07Z3* Extraction of Products of Conception, Low Forceps, Via Natural or Artificial Opening
  10D07Z4* Extraction of Products of Conception, Mid Forceps, Via Natural or Artificial Opening
  10D07Z5* Extraction of Products of Conception, High Forceps, Via Natural or Artificial Opening
  10D07Z6* Extraction of Products of Conception, Vacuum, Via Natural or Artificial Opening
  10D07Z7* Extraction of Products of Conception, Internal Version, Via Natural or Artificial Opening
  10D07Z8* Extraction of Products of Conception, Other, Via Natural or Artificial Opening
  10D17Z9  Manual Extraction of Products of Conception, Retained, Via Natural or Artificial Opening
  10D18Z9  Manual Extraction of Products of Conception, Retained, Via Natural or Artificial Opening Endoscopic
  10E0XZZ* Delivery of Products of Conception, External Approach
`
Let me know if this helps. 
Will close the case for the moment.
