### ISSUE TITLE
NoExcl in Appendix C?

### ISSUE THREAD

**Issue by Raghu17s** [yubin-park/drgpy#5]
Hi folks,

I have ICD_Dx_lst = ['T6591XA','F23'] and when I try to find DRG it's showing _KeyError: 'No Excl_'. When I check the Appendix C, column "PDX Exclusions", "F23" is "NoExcl ".
So it is not writing any DRG.

How to I come out of KeyError: 'No Excl' and get proper DRG?

**Comment by yubin-park** [comment]
@Raghu17s Thanks for finding the bug. I updated a new version by changing line 56 of `drg.py`
`if pdx not in self.exmap.get(cc_info["pdx"],[])` is the changed line.
It seems that particular issue is resolved, but keep letting me know if you find more. Thanks!
(you should pull the latest version from Github).

**Comment by Raghu17s** [comment]
Hey,
The other solution is to replace appendix files and MDC files in folder "/data" with latest MSDRG v37 release files.

It worked for me. I would suggest to update the MSDRG files. 

Thanks

**Comment by yubin-park** [comment]
@Raghu17s I just updated the data files to v37.2 - I needed to change some parsing logic as CMS removed some DRGs and applied different logics here and there. I tested my own, but please let me know if something goes wrong. Thanks!
(you would need to pull the latest version)
