### ISSUE TITLE
Making OR Procedures DRG-specific

### ISSUE THREAD

**Issue by mperryman-alivia** [yubin-park/drgpy#7]
Hey thanks for this package - simple, clean API which can chug through DRG grouping very quickly.

I cross referenced the results with already grouped DRGs and came across a few issues:

1. **OR Procedures are DRG-specific:** After skimming through your code, it seems like the logic for Appendix E is implemented in a way where it considers procedures as OR or non-OR despite this distinction being DRG-specific. I noticed common misclassification into DRG 819 due to this.
2. **DRG-specific Issues:** There are a handful of DRGs which have minor issues in their implementation
      a. **795:** The claim still qualifies for this DRG if it has multiple secondary diagnoses which are on the list of allowed secondaries. It is not simply a hard cut off with more than one
      b. **064 and 065:** These DRGs qualify if they have rtPA OR an MCC/CC respectively. Currently claims are only qualifying if they have rtPA
      c. **177:** The second group of primary diagnoses is not being cross referenced for this grouping

Again - this is an awesome repo man, I've had to parse CMS files too and know it's no easy feat!

**Comment by yubin-park** [comment]
@mperryman-alivia Thanks so much for reviewing the code. In fact, I wasn't always sure if I was interpreting the DRG document correctly - it was very cryptic...
Your comments help a lot. I will take another look to fix those issues.

**Comment by mperryman-alivia** [comment]
Agreed - and it only gets more confusing once you start to consider the various forms of commercial DRG systems as well as APR DRGs (which are typically used by Medicaid Units).

Thanks for looking into this. If I have time I'll continue to review more of the discrepancies so we can group all ~750 DRGs correctly.

**Comment by michaelcgao** [comment]
mperryman, yubin, I noticed that as an example:

A case with PDx I63.232, SDx G81.91, and PPx 03CL0ZZ, gets grouped into MS-DRG 023. My understanding was that it should be grouped into DRG 038, or without the procedure, DRG 032.  Can you verify if this is accurate?  It's also helping me use specific cases to go through the logic.

**Comment by yubin-park** [comment]
@mperryman-alivia I tried to address most of the issues in the latest commit. Let me know if you see other issues. Sorry for the delayed response.

@michaelcgao I looked up ICD10-CD I63232 and it seems to map 023 or 024 depending on MCC. If not, please make another issue on the page. I will take a look at it again. 

Thanks for using the library and finding the bugs. Will close the issue for now.
