### ISSUE TITLE
Appropriately recognizing DRGs 98X (Procedure Unrelated to Primary Diagnosis)

### ISSUE THREAD

**Issue by jrincon-hekking** [yubin-park/drgpy#8]
This is awesome repo and much easier to implement than generating batch input for the MCE, but I've found a couple issues as compared to the official CMS logic. The most frequent issue we have encountered is inappropriate assignment (or rather lack thereof) to DRGs 981-983 and 987-989. It seems that with the current logic if the grouper finds a diagnosis that matches a DRG and sees that the procedures do not correspond to any DRGs directly related to that diagnosis, it ignores the procedures and returns a DRG just based on diagnosis codes. However, the correct logic would be to check if the unrelated procedure codes qualify for DRGs in the 98X range.

Example:
- DRGpy = Seizure + Coronary intervention --> DRG 101
- MSDRG/MCE = Seizure + Coronary intervention --> DRG 983

**Comment by jrincon-hekking** [comment]
I am working on implementing a fix for this and several other errors we've run into (handling many dx codes appropriately, deceased patient, minor misses for some DRGs), but the program logic is a bit opaque at times so we're not sure where it would be most efficient to add this reasoning. Would be interested in hearing what you'd recommend

**Comment by yubin-park** [comment]
@jrincon-hekking I pushed a new branch, and I think the new version should address the issue you found. I will close the issue for now, and let us know if you still see the same issue. Thanks!
